### ISSUE TITLE
Async/await

### ISSUE THREAD

**Issue by vuleticd** [nordsoftware/react-boilerplate#31]
Async / await is not just for managing promises. It is the way to control synchronous / asynchronous  execution on parts of the code.

Note that **await** may only be used in functions marked with the **async** keyword.

```js
// with 
function sleep(ms) {
  // Promise here is just to accomplish the sleep functionality
  return new Promise(resolve => setTimeout(resolve, ms));
}
async function bar(x) {
    await sleep(2000); // wait for 2 seconds then return
    return x;
}
// this is incorrect, await is used without function being declared as async, will throw an error
function foo(x) {
    await bar(x);
}
// this is correct
async function foo(x) {
    await bar(x);
}
```

By marking the function as async,, we are able to use await ( or not ) to control if the functions called inside will be executed in synchronous or asynchronous manner. 

```js
// will return 2x after 2 seconds
async function add1(x) {
  var a = bar(x);
  var b = bar(x);
  return await a + await b; 
}

// returns 2x after 4 seconds.
async function add1(x) {
  var a = await bar(x);
  var b = await  bar(x); // starts after a is done
  return a + b;
}
```

This makes it possible to change the sync/async flow simply by adding or omitting await before the function call.

**Comment by hugovk** [comment]
Closing, this project is deprecated. Please use [Create React App](https://github.com/facebook/create-react-app) instead.
