### ISSUE TITLE
A bug with production builds when using css-modules on Webpacks' css-loader

### ISSUE THREAD

**Issue by mika-lindell** [nordsoftware/react-boilerplate#50]
[https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/386](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/386)

Can be fixed by upgrading `extract-text-plugin` `^2.1.0` to enable `ignoreOrder`-flag ([https://github.com/webpack-contrib/extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin))

Then edit config in `webpack/production.babel.js` for example:
`const extractStylesPlugin = new ExtractTextPlugin({filename: '[name].[hash].css', ignoreOrder: true})`

**Comment by hugovk** [comment]
@mika-lindell Would you like to create a PR? Thanks!

**Comment by mika-lindell** [comment]
Pull request:
https://github.com/nordsoftware/react-boilerplate/pull/51

**Comment by cniska** [comment]
Closing this issue as the PR was already merged.
