### ISSUE TITLE
Documentation improvements (thoughts)

### ISSUE THREAD

**Issue by Kotpes** [nordsoftware/react-boilerplate#64]
If we want other folks to use this awesome boilerplate, documentation should to be written and structured in a way that takes through every step (ideally, without jumping back and fourth) to a stage where all the *essentials* are set up, app is running and user knows where to look for information to proceed.
Right now information is scattered among [Table of contents](https://github.com/digiaonline/react-boilerplate/blob/master/docs/README.md) with essential tools and optional tools are mixed together.

1. Clone project & run _these_ lines to get everything installed
2. Folder structure with explanation _why_ it's like that and what each file does
3. How to start the whole thing (with introduction of essential modules/components)
4. Possible next steps to take
5. Links to non-essential modules and how can they be used with this boilerplate
We have most of that information already, it's just fragmented and scattered over docs.
Ideally, a beginner should be able to set up a project just by reading the doc and have a clear understanding where he/she can find information to proceed

**Comment by cniska** [comment]
@Kotpes would you be willing to do this? All the information should already be scattered around the `docs` folder.

**Comment by Kotpes** [comment]
@crisu83 Can do, probably, some of it at least.
Not sure about the reasoning behind certain things, e.g. in `index.js`:
```js
import type {RootProps} from './root/components/Root'

const rootProps = {
  store: configureStore(),
}

const renderApp = (component: any, props: RootProps) =>
  render(
    <AppContainer>
      {createElement(component, props)}
    </AppContainer>,
    document.getElementById('root')
  )

renderApp(Root, rootProps)
```
Some other parts too

**Comment by cniska** [comment]
@Kotpes That's ok. You can do most of it and leave those details to me in that case.

**Comment by cniska** [comment]
@Kotpes We could consider adding some inline documentation in the code, especially in `root` folder. That's what they did for the configuration part in CRA.

**Comment by Kotpes** [comment]
@crisu83 IMHO now there are too many inline comments - distracts from reading code

**Comment by cniska** [comment]
@Kotpes are you talking about the Webpack configuration? That's out of our hands, because it comes directly from CRA.

**Comment by Kotpes** [comment]
@crisu83 Damn! Ok

**Comment by hugovk** [comment]
Closing, this project is deprecated. Please use [Create React App](https://github.com/facebook/create-react-app) instead.
